-- =============================================================================
-- Phase 3 schema — the life model
--
-- Replaces flat memory with a structured digital twin. Three core conventions
-- appear across most tables:
--
--   * Time-awareness: every observation has a `created_at`, and observations
--     that describe a moment in time also have an `observed_at`. Slowly-
--     changing facts use `updated_at`.
--
--   * Confidence-awareness: rows from explicit user input get confidence 1.0;
--     AI-inferred rows get a lower score so the agent can hedge appropriately.
--
--   * Source-awareness: every row records where it came from (`source`) and
--     who decided to write it (`created_by`).
--
-- Audit & correction: rows are not destructively edited. A correction creates
-- a new row and marks the original `superseded = true`. The agent reads only
-- non-superseded rows by default. This preserves history.
--
-- Run AFTER schema.sql and schema_phase2.sql. The legacy `memories` table
-- stays as an unstructured catch-all for facts that don't fit a schema.
-- =============================================================================


-- =============================================================================
-- 1. Identity
--
-- Single row per user. The "current truth" snapshot of who the person is.
-- JSONB profile so we can extend without migrations. Narrative is a short
-- AI-generated paragraph the agent reads to ground itself; regenerated by
-- the reflection engine in later phases.
-- =============================================================================

create table if not exists user_identity (
    user_id uuid primary key references auth.users on delete cascade,
    profile jsonb not null default '{}'::jsonb,
    narrative text,
    updated_at timestamptz default now() not null
);

alter table user_identity enable row level security;
drop policy if exists "own identity" on user_identity;
create policy "own identity" on user_identity
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- =============================================================================
-- 2. Emotional state — fixed core + extensible dimensions
--
-- The core three (mood, energy, stress) are typed columns so common queries
-- ("mood trend over last 30 days") stay fast and simple. Additional axes
-- (focus, social_battery, anxiety, motivation, etc.) live in `dimensions`
-- jsonb, which means adding a new axis tomorrow is zero migration cost.
--
-- source distinguishes self-report from inferred from passive (Phase 7).
-- The agent must treat inferred rows as hypotheses, not facts.
-- =============================================================================

create table if not exists emotional_state (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references auth.users on delete cascade not null,

    -- Core axes, -5 to +5. Nullable individually — a quick check-in might
    -- only capture mood, not all three.
    mood smallint check (mood between -5 and 5),
    energy smallint check (energy between -5 and 5),
    stress smallint check (stress between -5 and 5),

    -- Optional extra axes. Example:
    --   { "focus": 3, "social_battery": -2, "anxiety": 1 }
    -- We don't enforce a schema on this field — the agent decides what's
    -- worth recording. New axes graduate to typed columns only if they
    -- prove durably useful.
    dimensions jsonb default '{}'::jsonb,

    -- Free-text "why" — usually the highest-signal column long-term.
    note text,

    -- Discrete tags: ["work_stress", "post_workout", "lonely"].
    tags text[] default array[]::text[],

    source text not null check (source in ('self_report', 'inferred', 'passive')),
    created_by text not null check (created_by in ('user', 'assistant')) default 'user',
    confidence real check (confidence between 0 and 1) default 1.0,

    -- Audit trail: corrections supersede earlier rows rather than overwriting.
    superseded boolean default false not null,
    superseded_at timestamptz,

    observed_at timestamptz default now() not null,
    created_at timestamptz default now() not null
);

create index if not exists emotional_state_user_observed_idx
    on emotional_state (user_id, observed_at desc)
    where superseded = false;

alter table emotional_state enable row level security;
drop policy if exists "own emotional state" on emotional_state;
create policy "own emotional state" on emotional_state
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- =============================================================================
-- 3. People — relationship graph (nodes)
--
-- Each row is one person. The user is implicit (always you). Importance
-- lets the agent prioritize: when the system knows 50 people, who counts most?
--
-- emotional_significance is separate from importance — your therapist might
-- be a 9 on importance but a 5 on emotional_significance; your estranged
-- parent might be a 4 on importance but a 10 on emotional_significance.
-- They're different dimensions and worth keeping separate.
-- =============================================================================

create table if not exists people (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references auth.users on delete cascade not null,

    name text not null,
    relationship text,  -- "wife", "co-founder", "old friend"

    importance smallint check (importance between 1 and 10) default 5,
    emotional_significance smallint check (emotional_significance between 1 and 10) default 5,

    birthday date,

    -- Free-shape: phone, email, kids' names, work, hobbies, family links.
    -- Example links: { "spouse_of": "<uuid>", "parent_of": ["<uuid>"] }
    details jsonb default '{}'::jsonb,

    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

create index if not exists people_user_importance_idx
    on people (user_id, importance desc);

alter table people enable row level security;
drop policy if exists "own people" on people;
create policy "own people" on people
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- Notes about specific people. Many notes per person.
-- This is "remember last time we spoke about X" territory.
create table if not exists relationship_notes (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references auth.users on delete cascade not null,
    person_id uuid references people on delete cascade not null,

    content text not null,
    kind text not null check (kind in (
        'fact',            -- "Anna's kids are Maya and Leo"
        'recent_event',    -- "Had coffee yesterday, talked about her promotion"
        'sentiment',       -- "Has seemed distant lately"
        'follow_up'        -- "Should check in on her dad's surgery next week"
    )),

    source text not null check (source in ('self_report', 'inferred', 'chat')),
    created_by text not null check (created_by in ('user', 'assistant')) default 'assistant',
    confidence real check (confidence between 0 and 1) default 1.0,

    superseded boolean default false not null,
    superseded_at timestamptz,

    created_at timestamptz default now() not null
);

create index if not exists relationship_notes_user_person_idx
    on relationship_notes (user_id, person_id, created_at desc)
    where superseded = false;

alter table relationship_notes enable row level security;
drop policy if exists "own relationship notes" on relationship_notes;
create policy "own relationship notes" on relationship_notes
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- =============================================================================
-- 4. Life timeline — events that matter
--
-- Append-only log of meaningful events. Wedding. Started new job. Moved.
-- Tough conversation with mom. Big realization at 3am.
--
-- The journal (Phase 4) is the primary writer; users can also add manually.
-- =============================================================================

create table if not exists life_events (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references auth.users on delete cascade not null,

    title text not null,
    description text,

    category text check (category in (
        'milestone',     -- got married, graduated, launched
        'transition',    -- moved, new job, relationship change
        'loss',          -- death, breakup, layoff
        'achievement',   -- promotion, finished marathon
        'reflection',    -- "realized I want to leave consulting"
        'health',        -- diagnosis, recovery
        'other'
    )),
    tags text[] default array[]::text[],

    happened_on date not null,
    significance smallint check (significance between 1 and 10) default 5,

    source text check (source in ('self_report', 'inferred', 'chat')) default 'self_report',
    created_by text not null check (created_by in ('user', 'assistant')) default 'user',
    created_at timestamptz default now() not null
);

create index if not exists life_events_user_date_idx
    on life_events (user_id, happened_on desc);

alter table life_events enable row level security;
drop policy if exists "own life events" on life_events;
create policy "own life events" on life_events
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- =============================================================================
-- 5. Goals — life direction, with periodic check-ins for trend
--
-- Goals are first-class because they anchor the executive-function pillar.
-- "Become healthier" → the assistant knows this and reasons accordingly.
--
-- Progress is NOT a stored column. It's derived from goal_check_ins so it
-- stays correct as data flows in and so we can compute different views
-- (last 4 weeks, since last review, etc.).
--
-- alignment is a jsonb field intended for future use. Example:
--   { "values": ["growth"], "identity": ["founder"] }
-- We won't surface a numerical "alignment score" — see PHASE3_NOTES.md.
-- =============================================================================

create table if not exists goals (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references auth.users on delete cascade not null,

    title text not null,
    description text,

    horizon text not null check (horizon in (
        'week', 'month', 'quarter', 'year', 'multi_year', 'life'
    )),
    status text not null default 'active' check (status in (
        'active', 'paused', 'achieved', 'abandoned'
    )),

    -- How emotionally important this goal is, 1–10. Different from horizon.
    -- A weekly goal can be a 10 emotionally; a yearly one might be a 4.
    emotional_weight smallint check (emotional_weight between 1 and 10) default 5,

    -- Free-shape future field. Don't depend on a fixed shape yet.
    alignment jsonb default '{}'::jsonb,

    target_date date,

    -- Placeholder for future tasks/projects linkage:
    --   tasks table will have goal_id uuid references goals(id) on delete set null
    --   projects table will have goal_id uuid references goals(id) on delete set null
    -- Adding those tables in Phase 5 won't require touching this one.

    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

create index if not exists goals_user_status_idx
    on goals (user_id, status, created_at desc);

alter table goals enable row level security;
drop policy if exists "own goals" on goals;
create policy "own goals" on goals
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- Per-goal periodic check-ins. This is the substrate for progress trends.
-- The assistant reviews goals in weekly briefings (Phase 5+) and writes
-- one check-in per goal it discussed.
create table if not exists goal_check_ins (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references auth.users on delete cascade not null,
    goal_id uuid references goals on delete cascade not null,

    -- Where the user feels they are on this goal, -5 to +5.
    -- -5 = sliding backward, 0 = stuck, +5 = strong forward motion.
    -- Nullable: a check-in might be purely qualitative.
    momentum smallint check (momentum between -5 and 5),

    note text,

    source text not null check (source in ('self_report', 'inferred', 'chat')),
    created_by text not null check (created_by in ('user', 'assistant')) default 'assistant',

    created_at timestamptz default now() not null
);

create index if not exists goal_check_ins_user_goal_idx
    on goal_check_ins (user_id, goal_id, created_at desc);

alter table goal_check_ins enable row level security;
drop policy if exists "own goal check ins" on goal_check_ins;
create policy "own goal check ins" on goal_check_ins
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- =============================================================================
-- 6. Self-reflection log — the assistant's notes on its own performance
--
-- Written periodically by the reflection engine (a scheduled job in later
-- phases). Captures things like "user responds well to concise answers",
-- "morning briefings work; evening ones felt intrusive", "user finds the
-- mood check-in valuable but skips when stressed — paradoxical."
--
-- The agent reads from this table when shaping its own behavior.
-- =============================================================================

create table if not exists self_reflections (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references auth.users on delete cascade not null,

    content text not null,
    kind text not null check (kind in (
        'what_works',          -- "User responds well to direct, concise answers"
        'what_doesnt',         -- "User finds nudges intrusive after 9pm"
        'pattern_noticed',     -- "User journals more on Sundays"
        'open_question'        -- "Is the user venting or asking for help?"
    )),

    covers_period_start date,
    covers_period_end date,
    created_at timestamptz default now() not null
);

create index if not exists self_reflections_user_kind_idx
    on self_reflections (user_id, kind, created_at desc);

alter table self_reflections enable row level security;
drop policy if exists "own self reflections" on self_reflections;
create policy "own self reflections" on self_reflections
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- =============================================================================
-- 7. get_user_context — single-query life model snapshot
--
-- The agent calls this once per chat turn to get a coherent picture of the
-- user, instead of issuing 7 separate queries. Returns jsonb so the agent
-- can pass it directly into a system prompt.
-- =============================================================================

create or replace function get_user_context(
    p_user_id uuid,
    p_mood_days int default 14
)
returns jsonb
language sql
stable
as $$
    select jsonb_build_object(
        'identity', (
            select jsonb_build_object(
                'profile', profile,
                'narrative', narrative,
                'updated_at', updated_at
            )
            from user_identity where user_id = p_user_id
        ),
        'recent_mood', (
            select coalesce(jsonb_agg(jsonb_build_object(
                'mood', mood, 'energy', energy, 'stress', stress,
                'dimensions', dimensions,
                'note', note, 'observed_at', observed_at,
                'source', source, 'confidence', confidence
            ) order by observed_at desc), '[]'::jsonb)
            from emotional_state
            where user_id = p_user_id
              and superseded = false
              and observed_at > now() - (p_mood_days || ' days')::interval
        ),
        'active_goals', (
            select coalesce(jsonb_agg(jsonb_build_object(
                'id', id, 'title', title, 'horizon', horizon,
                'emotional_weight', emotional_weight,
                'target_date', target_date
            ) order by emotional_weight desc), '[]'::jsonb)
            from goals
            where user_id = p_user_id and status = 'active'
        ),
        'important_people', (
            select coalesce(jsonb_agg(jsonb_build_object(
                'id', id, 'name', name, 'relationship', relationship,
                'importance', importance,
                'emotional_significance', emotional_significance
            ) order by importance desc), '[]'::jsonb)
            from people
            where user_id = p_user_id and importance >= 7
        ),
        'recent_events', (
            select coalesce(jsonb_agg(jsonb_build_object(
                'title', title, 'category', category,
                'happened_on', happened_on, 'significance', significance
            ) order by happened_on desc), '[]'::jsonb)
            from life_events
            where user_id = p_user_id
              and happened_on > now() - interval '90 days'
        ),
        'recent_self_reflections', (
            select coalesce(jsonb_agg(jsonb_build_object(
                'content', content, 'kind', kind, 'created_at', created_at
            ) order by created_at desc), '[]'::jsonb)
            from self_reflections
            where user_id = p_user_id
              and created_at > now() - interval '60 days'
            limit 10
        )
    );
$$;
